### ISSUE TITLE
No unit or integration tests exist for training

### ISSUE THREAD

**Issue by oliverwm1** [ai2cm/FourCastNet#16]
Hard to know if new features are breaking code (e.g. #15). It would be helpful to have a simple end-to-end test of the training code. We could create some mock test data (perhaps define a test `Dataset` that returns appropriately shaped samples) and make sure that `Trainer.train()` runs without crashing. We could also verify that the trained model produces the same outputs (e.g. by hashing the prediction) but I would suggest to leave this to a subsequent PR to simplify initial implementation.

**Comment by gideonite** [comment]
Got started on [this branch](https://github.com/ai2cm/FourCastNet/tree/integration-test). Would be great to confirm that this is what you had in mind. @oliverwm1

**Comment by oliverwm1** [comment]
Thanks @gideonite! Yes that is exactly what I was thinking. Would be great if we can choose data/model/training parameters such that the test runs fast (< 10s).

**Comment by oliverwm1** [comment]
Resolved by #20
